//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/NickCuthbert/IdeaProjects/ProtobufGrammar/src\ProtocolBuffers3.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WhereIsMyTransport.Protobuf {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IProtocolBuffers3Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class ProtocolBuffers3BaseListener : IProtocolBuffers3Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionName([NotNull] ProtocolBuffers3Parser.OptionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.optionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionName([NotNull] ProtocolBuffers3Parser.OptionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] ProtocolBuffers3Parser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] ProtocolBuffers3Parser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldName([NotNull] ProtocolBuffers3Parser.FieldNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldName([NotNull] ProtocolBuffers3Parser.FieldNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyntax([NotNull] ProtocolBuffers3Parser.SyntaxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.syntax"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyntax([NotNull] ProtocolBuffers3Parser.SyntaxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportStatement([NotNull] ProtocolBuffers3Parser.ImportStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.importStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportStatement([NotNull] ProtocolBuffers3Parser.ImportStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.package"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackage([NotNull] ProtocolBuffers3Parser.PackageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.package"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackage([NotNull] ProtocolBuffers3Parser.PackageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.optionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionValue([NotNull] ProtocolBuffers3Parser.OptionValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.optionValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionValue([NotNull] ProtocolBuffers3Parser.OptionValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOption([NotNull] ProtocolBuffers3Parser.OptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOption([NotNull] ProtocolBuffers3Parser.OptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageType([NotNull] ProtocolBuffers3Parser.MessageTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.messageType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageType([NotNull] ProtocolBuffers3Parser.MessageTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumType([NotNull] ProtocolBuffers3Parser.EnumTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumType([NotNull] ProtocolBuffers3Parser.EnumTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] ProtocolBuffers3Parser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] ProtocolBuffers3Parser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldNumber([NotNull] ProtocolBuffers3Parser.FieldNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldNumber([NotNull] ProtocolBuffers3Parser.FieldNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOption([NotNull] ProtocolBuffers3Parser.FieldOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOption([NotNull] ProtocolBuffers3Parser.FieldOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldOptions([NotNull] ProtocolBuffers3Parser.FieldOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldOptions([NotNull] ProtocolBuffers3Parser.FieldOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.repeated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeated([NotNull] ProtocolBuffers3Parser.RepeatedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.repeated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeated([NotNull] ProtocolBuffers3Parser.RepeatedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] ProtocolBuffers3Parser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] ProtocolBuffers3Parser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneofField([NotNull] ProtocolBuffers3Parser.OneofFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.oneofField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneofField([NotNull] ProtocolBuffers3Parser.OneofFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOneof([NotNull] ProtocolBuffers3Parser.OneofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.oneof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOneof([NotNull] ProtocolBuffers3Parser.OneofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyType([NotNull] ProtocolBuffers3Parser.KeyTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.keyType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyType([NotNull] ProtocolBuffers3Parser.KeyTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMap([NotNull] ProtocolBuffers3Parser.MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMap([NotNull] ProtocolBuffers3Parser.MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] ProtocolBuffers3Parser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] ProtocolBuffers3Parser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRanges([NotNull] ProtocolBuffers3Parser.RangesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.ranges"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRanges([NotNull] ProtocolBuffers3Parser.RangesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReservedField([NotNull] ProtocolBuffers3Parser.ReservedFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReservedField([NotNull] ProtocolBuffers3Parser.ReservedFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReservedFields([NotNull] ProtocolBuffers3Parser.ReservedFieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedFields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReservedFields([NotNull] ProtocolBuffers3Parser.ReservedFieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReserved([NotNull] ProtocolBuffers3Parser.ReservedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReserved([NotNull] ProtocolBuffers3Parser.ReservedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum([NotNull] ProtocolBuffers3Parser.EnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.enum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum([NotNull] ProtocolBuffers3Parser.EnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] ProtocolBuffers3Parser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] ProtocolBuffers3Parser.EnumBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumField([NotNull] ProtocolBuffers3Parser.EnumFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumField([NotNull] ProtocolBuffers3Parser.EnumFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessage([NotNull] ProtocolBuffers3Parser.MessageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessage([NotNull] ProtocolBuffers3Parser.MessageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageBody([NotNull] ProtocolBuffers3Parser.MessageBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.messageBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageBody([NotNull] ProtocolBuffers3Parser.MessageBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterService([NotNull] ProtocolBuffers3Parser.ServiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.service"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitService([NotNull] ProtocolBuffers3Parser.ServiceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpc([NotNull] ProtocolBuffers3Parser.RpcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.rpc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpc([NotNull] ProtocolBuffers3Parser.RpcContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.topLevelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelDefinition([NotNull] ProtocolBuffers3Parser.TopLevelDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.topLevelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelDefinition([NotNull] ProtocolBuffers3Parser.TopLevelDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ProtocolBuffers3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProto([NotNull] ProtocolBuffers3Parser.ProtoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ProtocolBuffers3Parser.proto"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProto([NotNull] ProtocolBuffers3Parser.ProtoContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace WhereIsMyTransport.Protobuf
