//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/NickCuthbert/IdeaProjects/ProtobufGrammar/src\ProtocolBuffers3.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WhereIsMyTransport.Protobuf {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ProtocolBuffers3Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface IProtocolBuffers3Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.optionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionName([NotNull] ProtocolBuffers3Parser.OptionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] ProtocolBuffers3Parser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldName([NotNull] ProtocolBuffers3Parser.FieldNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.syntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyntax([NotNull] ProtocolBuffers3Parser.SyntaxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStatement([NotNull] ProtocolBuffers3Parser.ImportStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.package"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage([NotNull] ProtocolBuffers3Parser.PackageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionValue([NotNull] ProtocolBuffers3Parser.OptionValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] ProtocolBuffers3Parser.OptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.messageType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageType([NotNull] ProtocolBuffers3Parser.MessageTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumType([NotNull] ProtocolBuffers3Parser.EnumTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ProtocolBuffers3Parser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldNumber([NotNull] ProtocolBuffers3Parser.FieldNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOption([NotNull] ProtocolBuffers3Parser.FieldOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.fieldOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldOptions([NotNull] ProtocolBuffers3Parser.FieldOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.repeated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeated([NotNull] ProtocolBuffers3Parser.RepeatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] ProtocolBuffers3Parser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.oneofField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneofField([NotNull] ProtocolBuffers3Parser.OneofFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.oneof"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOneof([NotNull] ProtocolBuffers3Parser.OneofContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.keyType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyType([NotNull] ProtocolBuffers3Parser.KeyTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap([NotNull] ProtocolBuffers3Parser.MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] ProtocolBuffers3Parser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.ranges"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRanges([NotNull] ProtocolBuffers3Parser.RangesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedField([NotNull] ProtocolBuffers3Parser.ReservedFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.reservedFields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedFields([NotNull] ProtocolBuffers3Parser.ReservedFieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.reserved"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReserved([NotNull] ProtocolBuffers3Parser.ReservedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum([NotNull] ProtocolBuffers3Parser.EnumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] ProtocolBuffers3Parser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.enumField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumField([NotNull] ProtocolBuffers3Parser.EnumFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage([NotNull] ProtocolBuffers3Parser.MessageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.messageBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageBody([NotNull] ProtocolBuffers3Parser.MessageBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.service"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitService([NotNull] ProtocolBuffers3Parser.ServiceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.rpc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRpc([NotNull] ProtocolBuffers3Parser.RpcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.topLevelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelDefinition([NotNull] ProtocolBuffers3Parser.TopLevelDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProtocolBuffers3Parser.proto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProto([NotNull] ProtocolBuffers3Parser.ProtoContext context);
}
} // namespace WhereIsMyTransport.Protobuf
